---
title: "Use R to visualize the results of your meta-analysis"
date: "`r paste0(format(Sys.time(), '%d %B %Y'))`"
author: 'Kevin Cazelles, post-doc, McCann Lab, University of Guelph [<i class="fa fa-github" aria-hidden="true"></i>](https://github.com/KevCaz/graphsMetaAnalyses)'
# lang: french
output:
  ioslides_presentation:
    incremental: true
    widescreen: true
    includes:
      in_header: kcheader.html
    github: KevCaz
      #logo: ./img/logo.png
---




```{r, results = "hide", echo = FALSE, message = FALSE}
knitr::opts_chunk$set(
  fig.align='center',
  tidy=FALSE,
  comment="R>",
  size = 'small'
)
```


# R to visualize your data  

## Why visualize your data?

### A choice



## Why use R to do it?


Here we'll argue why use R for doing your plots:

  - visualizing data  
  - what makes a good graph (some details)  
  - work-flow (data are already in R)
  - base graph / ggplot2 / web graphs (interacting)
  - code / reproducible

  <i class="fa fa-github" aria-hidden="true"></i>


# Common plots used in meta-analyses (~ 20 min)

## Briefly

Here we'll review the common plots found in meta-analyses as well as the R packages one can use to create them:

  - histogram effect size / number of studies   
  - Funnel with Trim and Fill:   http://www.metafor-project.org/doku.php/plots:funnel_plot_with_trim_and_fill   
  - regression effect side against and a relevant factor    
  - `metafor` package   
  - authors contribution to the field   


# Funnel plot from scratch (~ 20 min)

## Funnel plot from scratch

During this section we'll try to create our own funnel plot:

  - par
  - background
  - axes
  - points/lines
  - titles
  - legend
  - landmarks
  - export your plot

# Let's practice (~ 30 min)

## reproduce one figure

may be the figures from Vellend et al. 2014 in PNAS


# Let's have some fun (~ 15 min)

## WordCloud

Here, I'll try to provide further insights. To do so,
we'll show a couple of plots such as:

  - Wordcloud
  - Network of co-authors


# Resources

## Useful links

- task view: https://cran.r-project.org/web/views/MetaAnalysis.html
- at least 3 books:

  1. Chen, Ding-Geng, and Karl E. Peace. [Applied Meta-Analysis with R](https://www.crcpress.com/Applied-Meta-Analysis-with-R/Chen-Peace/p/book/9781466505995). Chapman & Hall/CRC Biostatistics Series. Boca Raton: CRC Press/Taylor & Francis Group, 2013.  

  2. Schwarzer, Guido, James R. Carpenter, and Gerta Rücker. [Meta-Analysis with R](http://www.springer.com/us/book/9783319214153). Use R! Cham: Springer International Publishing, 2015. https://doi.org/10.1007/978-3-319-21416-0.



# That's all folks



<!-- ## cool

<div class="centered">
This text is centered.
</div>

## cool2

<div class="columns-2">

  - Bullet 1
  - Bullet 2
  - Bullet 3
</div> -->
